$BaseFolder =  "$PSScriptRoot\..\.."
$BaseModuleName = "QuickModuleCLI"
$NestedModulesFolder = "$BaseFolder\Modules"
$FunctionsFolder = "$BaseFolder\Root"
$PrivateFunctionsFolder = "$FunctionsFolder\Reserved"