$BaseFolder =  "$PSScriptRoot\..\.."
$BaseModuleName = "QuickModuleCLI"
$ModuleProjectsFolder = "$BaseFolder\Modules"
$FunctionsFolder = "$BaseFolder\Public"
$PrivateFunctionsFolder = "$BaseFolder\Private"